### ISSUE TITLE
Rename src directory to allow using repo as a git submodule

### ISSUE THREAD

**Issue by adolfogc** [sbougerel/spatial#3]
Renaming `src` -> `include/spatial` would allow for including the repository as a git submodule to avoid having to copy the files into the source tree.

**Comment by sbougerel** [comment]
Hey Adolfo, I just stumbled upon this.

It's never too late to take action. It's a neat idea, I'll do that.

Regards
Sylvain

**Comment by adolfogc** [comment]
Hi Sylvain, thank you for your reply and for considering my suggestion.

Best,
Adolfo
